name: code23_note_app
description: This project was developed by Alper Ragıb.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^5.3.3
  intl: ^0.18.1
  url_launcher: ^6.1.14
  cached_network_image: ^3.2.3
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^15.1.1
  material_color_generator: ^1.1.0
  fluttertoast: ^8.2.2
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0
  riverpod_infinite_scroll: ^1.0.9
  infinite_scroll_pagination: ^3.2.0
  flutter_staggered_grid_view: ^0.7.0
  adaptive_dialog: ^1.9.0+2



dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^2.1.1
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_android.png"
  image_path_android: "assets/images/icon_android.png"
  image_path_ios: "assets/images/icon_ios.jpg"
  remove_alpha_ios: true

flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  image: assets/images/icon_android.png
  image_gravity: center

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
